Fix some issues that have arisen over the years of use
    Replaced time type(system->wall)
    Fixed deprecated timer(header, usage)
    Fixed boost bind header
    Fix the number parsing in the EDBA postgresql backend
    Fix undefined reference to the sqlite3 systems
    Parse case for string with time only
    Add the new SDK version to the ODBC finder
    Force int initialization in edba
    tmp value should be set to zero before usage
    Use NO_SYSTEM_ENVIRONMENT_PATH in the ODBC cmake finder
    Raise error statement in stored proc results to opened cursor after SQLExecute returns -1
    Fix crash due to TIME(0) column type